import Head from 'next/head'
import Image from 'next/image'
import Evernote from './components/Evernote'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Evernote clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
            Evernote Clone
        </h1>
        <Evernote/>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
